import React from 'react';
import type { WeekdayIndices, Value } from '../../utils/types';
declare type CalendarViewProps = {
    viewDate: Date | undefined;
    className: string;
    isDualMode: boolean;
    useDarkMode: boolean;
    hideAdjacentDates: boolean;
    isSecondary: boolean;
    size: number;
    fontSize: number;
    onChangenNewSelectedRangeEnd: (date: Date | undefined) => unknown;
    onChangenNewSelectedRangeStart: (date: Date | undefined) => unknown;
    onChangenSelectedRangeStart: (date: Date | undefined) => unknown;
    onChangenSelectedRangeEnd: (date: Date | undefined) => unknown;
    onChangenSelectedMultiDates: (dates: Record<string, Date | undefined>) => unknown;
    onChangenSelectedDate: (dates: Date) => unknown;
    allowFewerDatesThanRange: boolean;
    skipDisabledDatesInRange: boolean;
    skipWeekendsInRange: boolean;
    weekStartIndex: WeekdayIndices;
    fixedRangeLength: number;
    selectedDate: Date | undefined;
    selectedRangeStart: Date | undefined;
    selectedRangeEnd: Date | undefined;
    newSelectedRangeStart: Date | undefined;
    newSelectedRangeEnd: Date | undefined;
    isRangeSelectorView: boolean;
    isFixedRangeView: boolean;
    weekendIndices: WeekdayIndices[];
    selectedMultiDates: Record<string, Date | undefined>;
    isMultiSelectorView: boolean;
    isRangeSelectModeOn: boolean;
    setIsRangeSelectModeOn: (on: boolean) => void;
    disableFuture: boolean;
    disablePast: boolean;
    disableToday: boolean;
    lockView: boolean;
    maxAllowedDate?: Date;
    minAllowedDate?: Date;
    highlights: Date[];
    isDisabled: (date: Date) => boolean;
    checkIfWeekend: (date: Date) => boolean;
    today: Date;
    onChange?: (value: Value) => unknown | Promise<unknown>;
    onPartialRangeSelect?: (value: Value) => unknown | Promise<unknown>;
    onEachMultiSelect?: (value: Value) => unknown | Promise<unknown>;
    value?: Value;
    isNormalView: boolean;
    highlightedDate: Date | undefined;
};
export default function Calendarview(props: CalendarViewProps): React.ReactElement<CalendarViewProps>;
export {};
